name: Configure zkSBOM tools

on:
  workflow_call:
    inputs:
      zksbom_operator_template:
        required: true
        type: string
      zksbom_operator_output:
        required: true
        type: string
      verifier_template:
        required: true
        type: string
      verifier_output:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:
  configure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: true

      - name: Configure zksbom-operator
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          sed \
            -e "s|YOUR_TOKEN|${GH_TOKEN}|g" \
            "${{ inputs.zksbom_operator_template }}" \
            > "${{ inputs.zksbom_operator_output }}"

      - name: Configure zksbom-verifier
        run: cp "${{ inputs.verifier_template }}" "${{ inputs.verifier_output }}"
